# Generated by Django 5.0.1 on 2024-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='section_or_area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Section or Area'),
        ),
    ]
